- name: Render local Brewfile
  ansible.builtin.template:
    src: "brewfile.j2"
    dest: "~/.Brewfile"
  register: brewfile

- name: Install packages via Homebrew
  ansible.builtin.shell: brew bundle --no-lock --file ~/.Brewfile
  when: brewfile.changed

- name: osx defaults
  include_tasks: "osx_defaults.yml"
  args:
    apply:
      tags:
        - osx_defaults

- name: copy wallpaper
  copy:
    src: wallpaper-nz.jpg
    dest: ~/Pictures/wallpaper-nz.jpg
  register: wallpaper_file

- name: use wallpaper
  when: wallpaper_file.changed
  ansible.builtin.shell: osascript -e 'tell application "Finder" to set desktop picture to POSIX file "{{wallpaper_file.dest}}"'